[package]
name = "rust_proxy"
version = "0.1.0"
authors = ["Leonardo Moraes Fleury <fleuryleomoraes@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.5.13"
dotenv = "0.13.0"
http-muncher = "0.3.2"