AMQP_URI: pyamqp://${RABBITMQ_USER:guest}:${RABBITMQ_PASSWORD:guest}@${RABBITMQ_HOST:localhost}
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
#rpc_exchange: 'notes-rpc'
max_workers: 10
parent_calls_tracked: 10

DATABASE: mongodb+srv://${MONGO_USER:users_admin}:${MONGO_PASSWORD:sHM3oaMqcM8PaTML}@${MONGO_HOST:notesdb-ytix1.gcp.mongodb.net/users?retryWrites=true}

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
    root:
        level: DEBUG
        handlers: [console]