[package]
name = "rust_proxy"
version = "0.1.0"
authors = ["Leonardo Moraes Fleury <fleuryleomoraes@gmail.com>"]

[dependencies]
# url = "1.7.1"
# httparse = "1.3.2"
log = "0.4"
env_logger = "0.5.13"
dotenv = "0.13.0"
http-muncher = "0.3.2"
# hyper = "0.12.9"